- name: PLAY 1 - View and Deploy SNMP
  hosts: devnetsandboxiosxe.cisco.com
  connection: network_cli
  gather_facts: no

  tasks:
   - name: Task 1 - Configure SNMP
    ios_config:
        commands: 
          - snmp-server community PUBLIC RO
          - snmp-server community PRIVATE RW





